### ISSUE TITLE
Change name to ofxOpenBCIReceiver as it doesn't contain code from openBCI

### ISSUE THREAD

**Issue by kyeshmz** [xlab-sfc/ofxOpenBCIReceiver#3]
データ・ドリブンでlibが入ってると誤解が生まれているために、名前変えて欲しいマン

**Comment by kyeshmz** [comment]
settings > transfer repositoryで渡せたら最高、もしくは組織にするか

**Comment by kentoids** [comment]
xlab-sfcにtransferしていい？
https://github.com/xlab-sfc

**Comment by kyeshmz** [comment]
いいよー
